<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="img\charfight.jpg" />
    <None Remove="img\loading.jpg" />
    <None Remove="img\MainWidowImg.png" />
    <None Remove="img\vs.jpg" />
    <None Remove="sound\GameBeginning.wav" />
    <None Remove="sound\menubutton.mp3" />
    <None Remove="sound\Movements.mp3" />
    <None Remove="sound\soundmarker33-war-horn-and-drums-512545.mp3" />
    <None Remove="sound\stregthen army.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\charfight.jpg" />
    <Resource Include="img\loading.jpg" />
    <Resource Include="img\MainWidowImg.png" />
    <Resource Include="img\vs.jpg" />
    <Content Include="sound\GameBeginning.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sound\menubutton.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sound\Movements.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sound\soundmarker33-war-horn-and-drums-512545.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sound\stregthen army.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HugoLand.Core\HugoLand.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Views\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
