// <auto-generated />
using System;
using HugoLand.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HugoLand.Core.Migrations
{
    [DbContext(typeof(HugoLandContext))]
    [Migration("20260515042524_NDB")]
    partial class NDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("HugoLand.Core.Domain.CombatEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackForce")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackLoss")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AttackRandomFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("DefenceForce")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenceLoss")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DefenceRandomFactor")
                        .HasColumnType("REAL");

                    b.Property<float>("EffectiveAttackForce")
                        .HasColumnType("REAL");

                    b.Property<float>("EffectiveDefenceForce")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoldLooted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerritoryDefendedPosX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerritoryDefendedPosY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VictorPlayerNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CombatEvents");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSizeX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSizeY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MilitaryVictory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerPlayerNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TerritoryId")
                        .IsUnique();

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.MilitaryDetachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanAct")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanMove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilitaryForce")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TerritoryId")
                        .IsUnique();

                    b.ToTable("MilitaryDetachments");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ForcesTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnInDept")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.PlayerAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerActions");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Territory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerritoryType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "PositionX", "PositionY")
                        .IsUnique();

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.TurnSnapShot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmyCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FortificationCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMilitaryForce")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("TurnSnapShots");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.CombatEvent", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("CombatEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Installation", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("Installations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HugoLand.Core.Domain.Player", "Player")
                        .WithMany("Installations")
                        .HasForeignKey("PlayerId");

                    b.HasOne("HugoLand.Core.Domain.Territory", "Territory")
                        .WithOne("Installation")
                        .HasForeignKey("HugoLand.Core.Domain.Installation", "TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.MilitaryDetachment", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("MilitaryDetachments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HugoLand.Core.Domain.Player", "Player")
                        .WithMany("MilitaryDetachments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HugoLand.Core.Domain.Territory", "Territory")
                        .WithOne("MilitaryDetachment")
                        .HasForeignKey("HugoLand.Core.Domain.MilitaryDetachment", "TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Player", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.PlayerAction", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("PlayerActions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Territory", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("Territories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.TurnSnapShot", b =>
                {
                    b.HasOne("HugoLand.Core.Domain.Game", "Game")
                        .WithMany("TurnSnapShots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Game", b =>
                {
                    b.Navigation("CombatEvents");

                    b.Navigation("Installations");

                    b.Navigation("MilitaryDetachments");

                    b.Navigation("PlayerActions");

                    b.Navigation("Players");

                    b.Navigation("Territories");

                    b.Navigation("TurnSnapShots");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Player", b =>
                {
                    b.Navigation("Installations");

                    b.Navigation("MilitaryDetachments");
                });

            modelBuilder.Entity("HugoLand.Core.Domain.Territory", b =>
                {
                    b.Navigation("Installation");

                    b.Navigation("MilitaryDetachment");
                });
#pragma warning restore 612, 618
        }
    }
}
